In [4]:
import numpy as np

#sigmoid
def sigmoid(x):
  return (1/(1+np.exp(-x)))

def derivatives_sigmoid(x):
  return (x*(1-x))
  
def random_init(size, low=0.0, high=1.0):
  return np.random.uniform(size=size, low=low, high=high)

learning_rate = 0.1

#Step 0
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y = np.array([[1],[1],[0]])

#Step 1
wh = random_init((4,3))
bh = random_init((1,3))
wout = random_init((3,1))
bout = random_init((1,1))

print("Input, X:\n",X)
print("Target Output, y:\n",y)
print("Hidden layer weight, wh:\n",wh)
print("Hidden layer bias, bh:\n",bh)
print("Output layer weight, wout:\n",wout)
print("Hidden layer bias, bout:\n",bout)

Input, X:
 [[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
Target Output, y:
 [[1]
 [1]
 [0]]
Hidden layer weight, wh:
 [[0.52919399 0.70531672 0.15258913]
 [0.2280877  0.3858858  0.756813  ]
 [0.50458037 0.28456721 0.38408604]
 [0.03891137 0.47025442 0.59676471]]
Hidden layer bias, bh:
 [[0.26064517 0.91777818 0.20565904]]
Output layer weight, wout:
 [[0.22877682]
 [0.26468692]
 [0.62626389]]
Hidden layer bias, bout:
 [[0.73695375]]


In [5]:
#Step 2
hidden_layer_input = np.dot(X, wh) + bh
print("Hidden layer input, hidden_layer_input:\n",hidden_layer_input)

Hidden layer input, hidden_layer_input:
 [[1.29441953 1.90766211 0.74233421]
 [1.3333309  2.37791653 1.33909892]
 [0.52764423 1.7739184  1.55923675]]


In [6]:
#Step 3
hiddenlayer_activations = sigmoid(hidden_layer_input)
print("Hidden layer activation, hiddenlayer_activations:\n",hiddenlayer_activations)

Hidden layer activation, hiddenlayer_activations:
 [[0.7848943  0.87075627 0.67750607]
 [0.79139107 0.91512775 0.79234172]
 [0.6289335  0.85494429 0.8262438 ]]


In [7]:
#Step 4
output_layer_input = np.dot(hiddenlayer_activations, wout ) + bout
output = sigmoid(output_layer_input)
print("Output layer input matrix, output_layer_input:\n",output_layer_input)
print("Output layer output matrix, output:\n",output)

Output layer input matrix, output_layer_input:
 [[1.57129476]
 [1.65644304]
 [1.62457839]]
Output layer output matrix, output:
 [[0.82796811]
 [0.83975995]
 [0.83542558]]


In [8]:
#Step 5
E = y-output
print("Error in training output, E:\n",E)

Error in training output, E:
 [[ 0.17203189]
 [ 0.16024005]
 [-0.83542558]]


In [9]:
#Step 6
Slope_output_layer= derivatives_sigmoid(output)
Slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
print("Slope of output layer's output, Slope_output_layer:\n",Slope_output_layer)
print("Slope of hidden layer's output , Slope_hidden_layer:\n",Slope_hidden_layer)

Slope of output layer's output, Slope_output_layer:
 [[0.14243692]
 [0.13456318]
 [0.13748968]]
Slope of hidden layer's output , Slope_hidden_layer:
 [[0.16883524 0.11253979 0.21849159]
 [0.16509124 0.07766895 0.16453632]
 [0.23337615 0.12401455 0.14356498]]


In [10]:
#Step 7
d_output = E * Slope_output_layer * learning_rate
print("Delta of output layer, d_output:\n",d_output)

Delta of output layer, d_output:
 [[ 0.00245037]
 [ 0.00215624]
 [-0.01148624]]


In [14]:
#Step 8
Error_at_hidden_layer = np.dot(d_output, wout.T)
print("Error in hidden layer's output, Error_at_hidden_layer:\n",Error_at_hidden_layer)

Error in hidden layer's output, Error_at_hidden_layer:
 [[ 0.00056059  0.00064858  0.00153458]
 [ 0.0004933   0.00057073  0.00135038]
 [-0.00262779 -0.00304026 -0.00719342]]


In [16]:
#Step 9
d_hiddenlayer = Error_at_hidden_layer * Slope_hidden_layer
print("Delta of hidden layer, d_hiddenlayer:\n",d_hiddenlayer)

Delta of hidden layer, d_hiddenlayer:
 [[ 9.46469568e-05  7.29911352e-05  3.35292347e-04]
 [ 8.14391791e-05  4.43279079e-05  2.22185887e-04]
 [-6.13262448e-04 -3.77036168e-04 -1.03272278e-03]]


In [18]:
#Step 10: Update weight at both output and hidden layer
wout = wout + np.dot(np.transpose(hiddenlayer_activations), d_output) * learning_rate
wh = wh+ np.dot(np.transpose(X), d_hiddenlayer) * learning_rate
print("New Output layer weight, wout:\n",wout)
print("New Hidden layer weight, wh:\n",wh)

New Output layer weight, wout:
 [[0.22805795]
 [0.26354429]
 [0.62503952]]
New Hidden layer weight, wh:
 [[0.5292292  0.70534018 0.15270063]
 [0.22796505 0.38581039 0.75660646]
 [0.50461559 0.28459067 0.38419754]
 [0.038805   0.47018788 0.5966026 ]]


In [19]:
#Step 11: Update biases at both output and hidden layer
bh = bh + np.sum(d_hiddenlayer, axis=0) * learning_rate
bout = bout + np.sum(d_output, axis=0) * learning_rate
print("New Output layer bias, bh:\n",bh)
print("New Output layer bias, bout:\n",bout)

New Hidden layer bias, bh:
 [[0.26060145 0.91775221 0.20561152]]
New Output layer bias, bout:
 [[0.73626579]]
