[View in Colaboratory](https://colab.research.google.com/github/GeniGaus/MLBlr/blob/master/ASSIGNMENT2B.ipynb)

In [5]:
import numpy as np

#sigmoid
def sigmoid(x):
  return (1/(1+np.exp(-x)))

def derivatives_sigmoid(x):
  return (x*(1-x))
  
def random_init(size, low=0.0, high=1.0):
  return np.random.uniform(size=size, low=low, high=high)

learning_rate = 0.1

#Step 0
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y = np.array([1,1,0])

#Step 1
wh = random_init((4,3))
bh = random_init((1,3))
wout = random_init((3,1))
bout = random_init((1,1))

print("Input, X:\n",X)
print("Target Output, y:\n",y)
print("Hidden layer weight, wh:\n",wh)
print("Hidden layer bias, bh:\n",bh)
print("Output layer weight, wout:\n",wout)
print("Hidden layer bias, bout:\n",bout)

Input, X:
 [[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
Target Output, y:
 [1 1 0]
Hidden layer weight, wh:
 [[0.77607807 0.31888591 0.89224266]
 [0.19516245 0.20622793 0.28196784]
 [0.22821902 0.70618933 0.80795593]
 [0.69571375 0.60144269 0.30560721]]
Hidden layer bias, bh:
 [[0.52206785 0.15062619 0.79765256]]
Output layer weight, wout:
 [[0.07400763]
 [0.97425401]
 [0.5487273 ]]
Hidden layer bias, bout:
 [[0.16085333]]


In [6]:
#Step 2
hidden_layer_input = np.dot(X, wh) + bh
print("Hidden layer input, hidden_layer_input:\n",hidden_layer_input)

Hidden layer input, hidden_layer_input:
 [[1.52636494 1.17570144 2.49785116]
 [2.22207869 1.77714413 2.80345837]
 [1.41294405 0.95829681 1.38522762]]


In [7]:
#Step 3
hiddenlayer_activations = sigmoid(hidden_layer_input)
print("Hidden layer activation, hiddenlayer_activations:\n",hiddenlayer_activations)

Hidden layer activation, hiddenlayer_activations:
 [[0.82147384 0.76417403 0.92399104]
 [0.90221474 0.85534387 0.94286242]
 [0.80422988 0.72278067 0.79982927]]


In [8]:
#Step 4
output_layer_input = np.dot(hiddenlayer_activations, wout ) + bout
output = sigmoid(output_layer_input)
print("Output layer input matrix, output_layer_input:\n",output_layer_input)
print("Output layer output matrix, output:\n",output)

Output layer input matrix, output_layer_input:
 [[1.47316738]
 [1.57832065]
 [1.36343259]]
Output layer output matrix, output:
 [[0.81353834]
 [0.82896655]
 [0.79631702]]


In [9]:
#Step 5
E = y-output
print("Error in training output, E:\n",E)

Error in training output, E:
 [[ 0.18646166  0.18646166 -0.81353834]
 [ 0.17103345  0.17103345 -0.82896655]
 [ 0.20368298  0.20368298 -0.79631702]]


In [10]:
#Step 6
Slope_output_layer= derivatives_sigmoid(output)
Slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
print("Slope of output layer's output, Slope_output_layer:\n",Slope_output_layer)
print("Slope of hidden layer's output , Slope_hidden_layer:\n",Slope_hidden_layer)

Slope of output layer's output, Slope_output_layer:
 [[0.15169371]
 [0.14178101]
 [0.16219622]]
Slope of hidden layer's output , Slope_hidden_layer:
 [[0.14665457 0.18021208 0.0702316 ]
 [0.0882233  0.12373074 0.05387288]
 [0.15744418 0.20036877 0.16010241]]


In [11]:
#Step 7
d_output = E * Slope_output_layer * learning_rate
print("Gradient descent of output layer, d_output:\n",d_output)

Gradient descent of output layer, d_output:
 [[ 0.00282851  0.00282851 -0.01234087]
 [ 0.00242493  0.00242493 -0.01175317]
 [ 0.00330366  0.00330366 -0.01291596]]


In [12]:
#Step 8
Error_at_hidden_layer = np.dot(d_output, wout)
print("Error in hidden layer's output, Error_at_hidden_layer:\n",Error_at_hidden_layer)

Error in hidden layer's output, Error_at_hidden_layer:
 [[-0.00380675]
 [-0.00390733]
 [-0.00362424]]


In [13]:
#Step 9
d_hiddenlayer = Error_at_hidden_layer * Slope_hidden_layer
print("Gradient descent of hidden layer, d_hiddenlayer:\n",d_hiddenlayer)

Gradient descent of hidden layer, d_hiddenlayer:
 [[-0.00055828 -0.00068602 -0.00026735]
 [-0.00034472 -0.00048346 -0.0002105 ]
 [-0.00057062 -0.00072618 -0.00058025]]


In [14]:
#Step 10: Update weight at both output and hidden layer
wout = wout + np.dot(np.transpose(hiddenlayer_activations), d_output) * learning_rate
wh = wh+ np.dot(np.transpose(X), d_hiddenlayer) * learning_rate
print("Output layer weight, wout:\n",wout)
print("Hidden layer weight, wh:\n",wh)

Output layer weight, wout:
 [[0.07472446 0.07472446 0.07089473]
 [0.97491636 0.97491636 0.97137212]
 [0.54948152 0.54948152 0.54544579]]
Hidden layer weight, wh:
 [[0.77598777 0.31876896 0.89219487]
 [0.19510538 0.20615531 0.28190982]
 [0.22812872 0.70607239 0.80790815]
 [0.69562222 0.60132172 0.30552814]]


In [15]:
#Step 11: Update biases at both output and hidden layer
bh = bh + np.sum(d_hiddenlayer, axis=0) * learning_rate
bout = bout + np.sum(d_output, axis=0) * learning_rate
print("Output layer bias, bh:\n",bh)
print("Output layer bias, bout:\n",bout)

Output layer bias, bh:
 [[0.52192049 0.15043663 0.79754675]]
Output layer bias, bout:
 [[0.16170904 0.16170904 0.15715233]]
